title: janto.github.com
description: Janto Dreijer
google_analytics: 
show_downloads: false
theme: jekyll-theme-hacker

github:
  is_project_page: false

gems:
  - jekyll-mentions

author:
  name: Janto Dreijer
  email: jantod@gmail.com
  github: janto
  twitter: janto_d
